<form name="secureframeform" method="post" action="<?php echo $this->getActionUrl(); ?>" target="securepay_secureframe">
	<?php
		foreach ($this->getSfRequest() as $key => $value) {
		    echo "<input type='hidden' name='$key' value='$value' />\n";
		}
	?>
</form>
<script type="text/javascript">
function hideLoadingMsg(){
	document.getElementById("loadingmsg").style.display = "none";
	document.getElementById("securepay_secureframe").style.display = "block";
}
</script>
<h1 id="loadingmsg">Loading payment form...</h1>
<iframe id="securepay_secureframe" name="securepay_secureframe" style="border:0;width:100%;height:500px" src="" onload="hideLoadingMsg()"></iframe>
<script type="text/javascript">
document.getElementById("securepay_secureframe").style.display = "none";
document.secureframeform.submit();
</script>